stages:
  - build
  - test
  - deploy

conda:
  image: continuumio/miniconda3:latest

  before_script:
    - apt-get update -q -y
    - apt-get install -y  gcc
    - apt-get install -y swig
    #- chmod +x conda-pipeline/miniconda.sh
    #- ./conda-pipeline/miniconda.sh

    #- conda env create -f environment.yaml
    #- source activate myenv


  stage:  build

  script:
    - conda install conda-build
    - echo $PWD
    - mkdir dist
    - mkdir dist/3.7
    - mkdir dist/3.6
    - mkdir dist/3.4
    - mkdir dist/2.7
    - conda config --set anaconda_upload no
    #- cd conda-pipeline
    - echo $PWD
    - conda build --python=3.7 conda-pipeline
    - cp /opt/conda/conda-bld/linux-64/jetset* /builds/andreatramacere/jetset/dist/3.7/
    - echo $PWD
    - conda build --python=3.6 conda-pipeline
    - cp /opt/conda/conda-bld/linux-64/jetset* /builds/andreatramacere/jetset/dist/3.6/
    - echo $PWD
    - conda build --python=3.4 conda-pipeline
    - cp /opt/conda/conda-bld/linux-64/jetset* /builds/andreatramacere/jetset/dist/3.4/
    - echo $PWD
    - conda build --python=2.7 conda-pipeline
    - cp /opt/conda/conda-bld/linux-64/jetset* /builds/andreatramacere/jetset/dist/2.7/

  artifacts:
    paths:
    - dist


  only:
  - py23

pip:
  image: python:3.6

  before_script:
  - apt-get update -q -y
  - apt-get install -y  gcc
  - apt-get install -y swig
  - pip install -r pip-pipeline/requirements.txt

  stage:  build

  artifacts:
    paths:
    - dist

  script:
  - python setup.py install

  only:
  - never